import cloudinary from 'cloudinary';
import dotenv from 'dotenv';

dotenv.config();

class CarController {
    saveOne(req,res,next){
        let result = 'File saved successfully '+ req.file.filename;
        console.log(req.file);

    
        cloudinary.config({
            cloud_name: process.env.CLOUD_NAME,
            api_key: process.env.API_KEY,
            api_secret: process.env.API_SECRET
        });
      
        cloudinary.uploader.upload('pizza.jpg', { tags: 'basic_sample' }, function (err, image) {
            console.log();
            console.log("** File Upload");
            if (err) { console.warn(err); }
            console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
            console.log("* " + image.public_id);
            console.log("* " + image.url);
           
          });

        res.status(200).json(result + ' '+ process.env.CLOUD_NAME);
    }

    getCars(req,res,next){

    }
}

export default new CarController();
