import cloudinary from 'cloudinary';
import dotenv from 'dotenv';

dotenv.config();

class CarController {
    saveOne(req,res,next){
        let result = 'File saved successfully '+ req.file.filename;
        console.log(req.file);
        console.log(req.file.path);

        cloudinary.config({
            cloud_name: process.env.CLOUD_NAME,
            api_key: process.env.API_KEY,
            api_secret: process.env.API_SECRET
        });
      
        cloudinary.uploader.upload(req.file.path, function (err, result) {
            console.log();
            console.log("** File Upload");
            if (err) { 
                console.warn(err); 
                res.status(404).json(err);
            }
            console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
            console.log(result);
            res.status(200).json(result);
           
          });
    }
    getCarImages(req,res,next){
        cloudinary.config({
            cloud_name: process.env.CLOUD_NAME,
            api_key: process.env.API_KEY,
            api_secret: process.env.API_SECRET
        });

        cloudinary.v2.api.resources(
            function(err,result){
                if(err) { res.status(404).json(err)}

                res.status(200).json(result);
            }
        )
    }

    getCarImage(req,res,next){
        let imageId = req.params.id;

        cloudinary.config({
            cloud_name: process.env.CLOUD_NAME,
            api_key: process.env.API_KEY,
            api_secret: process.env.API_SECRET
        });

        cloudinary.v2.api.resources_by_ids([imageId],
            function(err,result){
                if(err){
                    console.log(err);
                    res.status(404).json(err);
                }
              
                res.status(200).json(result);
            }
        )
        
    }
}

export default new CarController();
